name: ov_epaper
description: Command line app to download the ov epaper, since the images are available behind predictable url's.
version: 1.0.0
homepage: https://htoenjes.de

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
dependencies: 
  console: ^4.1.0
  dio: ^4.0.0
  intl: ^0.17.0
  pdf: ^3.4.2
