name: Dart build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, ARM]
        include:
          - os: ubuntu-latest
            output-name: ov-linux
            arch: x64
          - os: ARM
            output-name: ov-linux-arm
            arch: arm
          - os: macOS-latest
            output-name: ov-mac
            arch: x64
          - os: windows-latest
            output-name: ov-windows.exe
            arch: x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: dart pub get
      - name: Create build directory
        run: mkdir executables
      - name: Compile exe
        run: dart compile exe bin/ov_epaper.dart -o executables/${{ matrix.output-name }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: executables

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: executables
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ov-linux
            ov-linux-arm
            ov-mac
            ov-windows.exe
      
